# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['punch']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='modified',
            new_name='updated',
        ),
    ]
