# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_yarnissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('style', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField()),
                ('challan_no', models.CharField(max_length=20)),
                ('fabric_type', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=20)),
                ('dia_name', models.CharField(max_length=40)),
                ('fabric_construction', models.CharField(max_length=100)),
                ('received_grey_dia', models.CharField(max_length=100)),
                ('finished_fabric_dia', models.CharField(max_length=100)),
                ('finished_fabric_gsm', models.CharField(max_length=100, verbose_name='Finished Fabric GSM (color-wise)')),
                ('stitch_length', models.CharField(max_length=100)),
                ('stitch_color', models.CharField(max_length=100)),
                ('open_dia', models.BooleanField(default=False)),
                ('tube_dia', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
