# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='composition',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='lc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='spinning_mills',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
