# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20170921_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='YarnReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('challan_no', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('lc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.LCItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
