# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-04 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_yarnreceived'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('challan_no', models.CharField(max_length=20)),
                ('fabric_type', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=20)),
                ('dy_name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YarnDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('challan_no', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=20)),
                ('style_no', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('yr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.YarnReceived')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fabricdelivery',
            name='yd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.YarnDelivery'),
        ),
    ]
