# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20171015_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarnreceived',
            name='barcode',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
