# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0015_auto_20171114_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcitem',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lcitem',
            name='style_no',
            field=models.CharField(max_length=100),
        ),
    ]
