# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0018_auto_20171114_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricdelivery',
            name='fabric_construction',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricdelivery',
            name='finished_fabric_dia',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricdelivery',
            name='finished_fabric_gsm',
            field=models.CharField(default='', max_length=100, verbose_name='Finished Fabric GSM (color-wise)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricdelivery',
            name='open_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabricdelivery',
            name='received_grey_dia',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricdelivery',
            name='stitch_color',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricdelivery',
            name='stitch_length',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricdelivery',
            name='tube_dia',
            field=models.BooleanField(default=False),
        ),
    ]
