# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_auto_20170112_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='365/4, Road - 6, Baridhara DOHS, Dhaka - 1206', max_length=255),
            preserve_default=False,
        ),
    ]
