# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0005_auto_20170113_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
