# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0006_requisition_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
