# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0007_auto_20170205_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
