# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0010_auto_20180603_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequest',
            name='email',
            field=models.EmailField(default='michel@groupdesignace.com', max_length=254),
            preserve_default=False,
        ),
    ]
