# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-03 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0011_quotationrequest_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationrequestitem',
            old_name='qr',
            new_name='quotationrequest',
        ),
    ]
