# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 05:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170205_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.SmallIntegerField(choices=[(1, 'B +ve'), (2, 'B -ve'), (3, 'A +ve'), (4, 'A -ve'), (5, 'AB +ve'), (6, 'AB -ve'), (7, 'O +ve'), (8, 'O -ve')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Third Gender')], default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
