# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='cc_emails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(default='From Design Ace Limited', max_length=255),
        ),
    ]
