# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180424_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='body',
            field=models.TextField(default='No Content'),
        ),
    ]
