# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180514_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(default=b''),
        ),
    ]
