# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts_old_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
