# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europarts_old_2', '0002_auto_20170203_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductList',
            new_name='List',
        ),
    ]
