# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europarts_old_2', '0003_auto_20170205_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_view_original_price', 'Can view original price'), ('can_edit_original_price', 'Can edit original price'))},
        ),
    ]
