# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europarts_old_2', '0005_auto_20170206_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='original_price_available',
        ),
    ]
