# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0030_auto_20180408_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='display_id',
            field=models.IntegerField(default=5),
        ),
    ]
