# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20170417_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
