# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20170417_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='leavedays',
            old_name='user',
            new_name='employee',
        ),
    ]
