# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20170417_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leavedays',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='LeaveDays',
        ),
    ]
