# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-15 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_auto_20171015_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarndelivery',
            name='barcode',
            field=models.CharField(default='000000000000', max_length=50),
        ),
    ]
