# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_fabricdelivery_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcitem',
            name='color',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lcitem',
            name='style_no',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fabricdelivery',
            name='yd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.YarnDelivery', verbose_name='Yarn Delivered'),
        ),
        migrations.AlterField(
            model_name='yarndelivery',
            name='yr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.YarnReceived', verbose_name='Yarn Received'),
        ),
    ]
