# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-14 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0016_auto_20171114_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YarnDelivery',
            new_name='YarnIssue',
        ),
    ]
