# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-16 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0020_lcitem_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricdelivery',
            old_name='dy_name',
            new_name='dia_name',
        ),
    ]
