# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='part',
            name='type',
        ),
        migrations.RemoveField(
            model_name='worksheetrow',
            name='worksheet',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Worksheet',
        ),
        migrations.DeleteModel(
            name='WorksheetRow',
        ),
    ]
