# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0006_remove_list_original_price_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='public_price',
            new_name='selling_price',
        ),
    ]
