# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0007_quotation_worksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='quotation_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
