# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0008_auto_20170207_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='car_part',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_list',
        ),
        migrations.DeleteModel(
            name='CarPart',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
