# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('europarts', '0009_auto_20170207_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('part_no', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ref_no', models.CharField(max_length=20, unique=True)),
                ('cost_price_quoted', models.BooleanField(default=False)),
                ('selling_price_quoted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
                'permissions': (('can_add_product_list', 'Can add product list'),),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.SmallIntegerField()),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('cost_price', models.IntegerField(blank=True, null=True)),
                ('selling_price', models.IntegerField(blank=True, null=True)),
                ('car_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.CarPart')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.List')),
            ],
            options={
                'permissions': (('can_view_cost_price', 'Can view cost price'), ('can_add_cost_price', 'Can add cost price'), ('can_edit_cost_price', 'Can edit cost price'), ('can_view_selling_price', 'Can view selling price'), ('can_add_selling_price', 'Can add selling price'), ('can_edit_selling_price', 'Can edit selling price')),
            },
        ),
    ]
