# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0013_auto_20170405_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
