# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0014_auto_20170405_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetrow',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
