# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0015_worksheetrow_profit_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('Marine', 'Marine')], max_length=50, unique=True),
        ),
    ]
