# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0016_auto_20170417_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='engine_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
