# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0018_part_ship_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.ForeignKey(choices=[('Vehicle', 'Vehicle'), ('Marine', 'Marine')], on_delete=django.db.models.deletion.CASCADE, to='europarts.Type'),
        ),
    ]
