# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0020_auto_20170417_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='engine_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ship_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
