# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0021_auto_20170417_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='chassis_no',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='engine_no',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_no',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ship_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
