# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0022_auto_20170417_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheetrow',
            old_name='cost_price',
            new_name='air_freight_cost_p_pcs',
        ),
        migrations.RenameField(
            model_name='worksheetrow',
            old_name='profit_margin',
            new_name='gram_p_s',
        ),
        migrations.RenameField(
            model_name='worksheetrow',
            old_name='sale_price',
            new_name='net_purchase_price_taka',
        ),
        migrations.RemoveField(
            model_name='worksheetrow',
            name='type',
        ),
        migrations.AddField(
            model_name='worksheetrow',
            name='per_pcs_duty_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='worksheetrow',
            name='price_after_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='worksheetrow',
            name='total_price_in_taka',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='worksheetrow',
            name='unit_price_in_taka',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
