# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0024_auto_20170418_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheetrow',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worksheetrow',
            name='part_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
