# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0025_auto_20170418_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheetrow',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worksheetrow',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
