# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0031_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='europarts.Client'),
        ),
    ]
