# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0031_auto_20180408_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='display_id',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='display_id',
            field=models.IntegerField(default=5),
        ),
    ]
