# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0032_quotation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='recipient_address',
        ),
    ]
