# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0038_job_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReportEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
