# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0039_jobreportemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_report_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='JobReportEmail',
        ),
    ]
