# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0040_auto_20180816_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
