# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts', '0042_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheetrow',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
