# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('part_no', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AutoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ref_no', models.CharField(max_length=30, unique=True)),
                ('cost_price_quoted', models.BooleanField(default=False)),
                ('selling_price_quoted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
                'permissions': (('can_add_product_list', 'Can add product list'),),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.SmallIntegerField()),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('cost_price', models.IntegerField(blank=True, null=True)),
                ('selling_price', models.IntegerField(blank=True, null=True)),
                ('auto_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.AutoPart')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.List')),
            ],
            options={
                'permissions': (('can_view_cost_price', 'Can view cost price'),),
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ref_no', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.SmallIntegerField()),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('auto_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.AutoPart')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='autotype',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.Brand'),
        ),
        migrations.AddField(
            model_name='autopart',
            name='auto_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.AutoType'),
        ),
        migrations.AddField(
            model_name='autopart',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.Brand'),
        ),
        migrations.AlterUniqueTogether(
            name='autopart',
            unique_together=set([('brand', 'part_no')]),
        ),
    ]
