# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('europarts_old_2', '0002_auto_20170212_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='266832', max_length=6)),
                ('allowed', models.BooleanField(default=False)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europarts.Quotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created', 'permissions': (('can_view_cost_price', 'Can view cost price'),)},
        ),
        migrations.AlterUniqueTogether(
            name='quotationcode',
            unique_together=set([('quotation', 'user')]),
        ),
    ]
