# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts_old_2', '0005_auto_20170302_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationcode',
            name='work_order_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quotationcode',
            name='code',
            field=models.CharField(default='107839', max_length=6),
        ),
    ]
