# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts_old_2', '0008_auto_20170319_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationcode',
            name='code',
            field=models.CharField(default='134522', max_length=6),
        ),
    ]
