# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europarts_old_2', '0010_auto_20170321_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quotationcode',
            name='code',
            field=models.CharField(default='305971', max_length=6),
        ),
    ]
