# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_solved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('U', 'Unattended'), ('P', 'Solution Proposed'), ('A', 'Solution Accepted'), ('D', 'Solution Denied')], default='U', max_length=2),
        ),
    ]
