# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('emp_id', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('type', models.CharField(choices=[('N', 'Entry'), ('X', 'Exit'), ('L', 'Leave')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('emp_id', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('S', 'Sick'), ('C', 'Casual')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OffDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('details', models.CharField(default='Weekly Day Off', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together=set([('emp_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='attn',
            unique_together=set([('emp_id', 'date', 'type')]),
        ),
    ]
