# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attn',
            unique_together=set([]),
        ),
    ]
