# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20170525_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attn',
            old_name='date',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='attn',
            old_name='time',
            new_name='tm',
        ),
        migrations.AlterField(
            model_name='offday',
            name='details',
            field=models.CharField(default='Day Off', max_length=100),
        ),
    ]
