# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170528_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('sick_leave', models.SmallIntegerField()),
                ('casual_leave', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
