# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('SL', 'Sick'), ('CL', 'Casual')], default='SL', max_length=2),
        ),
    ]
